{"name": "test_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 0", "trace": "self = <test_mark_study.Test_Demo2 object at 0x0000023BEE801E48>\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.smoke\n    @pytest.mark.demo\n    def test_three(self):\n        b=2\n>       assert b==0#此用例会失败\nE       assert 2 == 0\n\ntest_mark_study.py:21: AssertionError"}, "start": 1619172423332, "stop": 1619172423332, "uuid": "92b4982c-d2b8-4e3d-a1f0-24739912e124", "historyId": "d0603abf5d44504edca8f801f6750d23", "testCaseId": "24f8059f5ad4462629bbfcc3d3bbe9b9", "fullName": "test_mark_study.Test_Demo2#test_three", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "demo"}, {"name": "tag", "value": "smoke"}, {"name": "suite", "value": "test_mark_study"}, {"name": "subSuite", "value": "Test_Demo2"}, {"name": "host", "value": "LAPTOP-SCD03LNF"}, {"name": "thread", "value": "9012-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_mark_study"}]}